# Generated by Django 2.1.5 on 2020-04-26 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flair_detector', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='upload_file',
        ),
    ]
